### ISSUE TITLE
Performance issues with a large number of metrics

### ISSUE THREAD

**Issue by rosaLux161** [timescale/timescale-prometheus#93]
We are faced with so many performance problems that after a few minutes the database is so busy that the queue can no longer be processed and the postgres server is no longer accessible.

## Steps to Reproduce

1. Installation of the TimescaleDB
2. Run of Timescale-Tune (Configuration output [postgresql.conf.txt](https://github.com/timescale/timescale-prometheus/files/4656885/postgresql.conf.txt))
3. Clone https://github.com/timescale/timescale-prometheus.git and compile ./extension (timescale-prometheus_extra)
4. Add timescale extension to postgres database
5. Download and run latest release of timescale-prometheus (0.1.0-alpha.3.1)
6. Add remote_write and remote_read to prometheus.yml

## Current Behavior
In the first minute, the metrics are accessible via the Prometheus UI, after that it takes a long time until the metrics are no longer accessible. This can also be observed in the log files:
[timescale-prometheus.log.txt](https://github.com/timescale/timescale-prometheus/files/4656927/timescale-prometheus.log.txt)
[prometheus.log.txt](https://github.com/timescale/timescale-prometheus/files/4656955/prometheus.log.txt)

## Context (Environment)
Specs: VM with 16 cores and 16 GB RAM
There are about 100 exporters in the scrapeconfig, which are queried every 15 seconds.

The setup was tried in the following constellations, which all gave the same result:

1) (VM1: Prometheus) <-> (VM2: Postgres, TimescaleDB Prometheus adapter)
2) (VM1: Prometheus, TimescaleDB Prometheus adapter) <-> (VM2: Postgres)
3) (VM: Prometheus, TimescaleDB Prometheus adapter, Postgres)

**Comment by cevian** [comment]
Hi @rosaLux161, Yes we are aware of the performance issues. We spent the last week optimizing it and have gotten a few orders-of-magnitude improvements. We should be merging the changes in starting this week and they should be part of the next release. In the meantime `experiment-split-create-metric` branch has our latest optimizations if you want to help us test whether it resolves your issues :).

**Comment by rosaLux161** [comment]
Thanks for the quick answer, @cevian . Unfortunately we can't get the branch to work. Once Prometheus sends data to the adapter, it crashes:

```
May 20 16:20:40 timescale-db-01 timescale-prometheus[14817]: using patched pgconn
May 20 16:20:40 timescale-db-01 timescale-prometheus[14817]: {"caller":"log.go:46","config":"&{listenAddr::9201 telemetryPath:/metrics pgmodelCfg:{host:localhost port:5432 user:prometheus password:**** database:prometheus sslMode:disable dbConnectRetries:0} logLevel:debug haGroupLockID:0 restElection:false prometheusTimeout:-1 electionInterval:5000000000 migrate:true}","level":"info","ts":"2020-05-20T14:20:40.087Z"}
May 20 16:20:40 timescale-db-01 timescale-prometheus[14817]: {"caller":"log.go:51","level":"warn","msg":"No adapter leader election. Group lock id is not set. Possible duplicate write load if running adapter in high-availability mode","ts":"2020-05-20T14:20:40.087Z"}
May 20 16:20:40 timescale-db-01 timescale-prometheus[14817]: {"caller":"log.go:46","level":"info","msg":"host=localhost port=5432 user=prometheus dbname=prometheus password='****' sslmode=disable connect_timeout=10","ts":"2020-05-20T14:20:40.120Z"}
May 20 16:20:40 timescale-db-01 timescale-prometheus[14817]: {"caller":"log.go:46","level":"info","msg":"Starting up...","ts":"2020-05-20T14:20:40.249Z"}
May 20 16:20:40 timescale-db-01 timescale-prometheus[14817]: {"addr":":9201","caller":"log.go:46","level":"info","msg":"Listening","ts":"2020-05-20T14:20:40.250Z"}
May 20 16:20:40 timescale-db-01 timescale-prometheus[14817]: panic: ERROR: column "possibly_new" does not exist (SQLSTATE 42703)
May 20 16:20:40 timescale-db-01 timescale-prometheus[14817]: goroutine 82 [running]:
May 20 16:20:40 timescale-db-01 timescale-prometheus[14817]: github.com/timescale/timescale-prometheus/pkg/pgmodel.runInserterRoutine(0xe0b220, 0xc00018a018, 0xc0005efd40, 0xc0001804a0, 0x16, 0xc00018c0e0)
May 20 16:20:40 timescale-db-01 timescale-prometheus[14817]:         /home/***/timescale-prometheus/pkg/pgmodel/pgx.go:393 +0x3d2
May 20 16:20:40 timescale-db-01 timescale-prometheus[14817]: created by github.com/timescale/timescale-prometheus/pkg/pgmodel.(*pgxInserter).getMetricInserter
May 20 16:20:40 timescale-db-01 timescale-prometheus[14817]:         /home/***/timescale-prometheus/pkg/pgmodel/pgx.go:341 +0x198
May 20 16:20:40 timescale-db-01 systemd[1]: prometheus-timescale-connector.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

**Comment by cevian** [comment]
ahh, @rosaLux161 you need to drop and recreate the postgres database for the branch to work

**Comment by sbaygithub** [comment]
I've tested this branch also with a similar setup like above and get the following error on startup:
```
./timescale-prometheus -db-host localhost -db-name prometheus -db-password prometheus -db-user prometheus
using patched pgconn
{"caller":"log.go:46","config":"&{listenAddr::9201 telemetryPath:/metrics pgmodelCfg:{host:localhost port:5432 user:prometheus password:**** database:prometheus sslMode:disable dbConnectRetries:0} logLevel:debug haGroupLockID:0 restElection:false prometheusTimeout:-1 electionInterval:5000000000 migrate:true}","level":"info","ts":"2020-05-22T07:14:25.028Z"}
{"caller":"log.go:51","level":"warn","msg":"No adapter leader election. Group lock id is not set. Possible duplicate write load if running adapter in high-availability mode","ts":"2020-05-22T07:14:25.028Z"}
{"caller":"log.go:46","level":"info","msg":"host=localhost port=5432 user=prometheus dbname=prometheus password='****' sslmode=disable connect_timeout=10","ts":"2020-05-22T07:14:25.065Z"}
{"caller":"log.go:46","level":"info","msg":"Starting up...","ts":"2020-05-22T07:14:25.218Z"}
{"addr":":9201","caller":"log.go:46","level":"info","msg":"Listening","ts":"2020-05-22T07:14:25.218Z"}
panic: missing metric table name

goroutine 1641 [running]:
github.com/timescale/timescale-prometheus/pkg/pgmodel.runInserterRoutine(0xe0b220, 0xc000010028, 0xc02d18a120, 0xc026d582d0, 0x4c, 0xc000038070)
	/opt/timescale-prometheus/pkg/pgmodel/pgx.go:393 +0x3d2
created by github.com/timescale/timescale-prometheus/pkg/pgmodel.(*pgxInserter).getMetricInserter
	/opt/timescale-prometheus/pkg/pgmodel/pgx.go:341 +0x198
```

After further testing I've got then after some time the following error:
```
2020/05/22 07:28:14 http: Accept error: accept tcp [::]:9201: accept4: too many open files; retrying in 5ms
2020/05/22 07:28:14 http: Accept error: accept tcp [::]:9201: accept4: too many open files; retrying in 10ms
2020/05/22 07:28:14 http: Accept error: accept tcp [::]:9201: accept4: too many open files; retrying in 20ms
2020/05/22 07:28:14 http: Accept error: accept tcp [::]:9201: accept4: too many open files; retrying in 40ms
2020/05/22 07:28:14 http: Accept error: accept tcp [::]:9201: accept4: too many open files; retrying in 80ms
2020/05/22 07:28:14 http: Accept error: accept tcp [::]:9201: accept4: too many open files; retrying in 160m
```

**Comment by cevian** [comment]
@sbaygithub This is fixed in #110
